### PR TITLE
Fix tertiary sidebar visibility

### LINKED ISSUE #197: secondary sidebar
I'm using primer in two separate locations. One is at GoDaddy, and the other is at work on an IIS server.

In both locations, the secondary sidebar content simply will not display.

I have selected a 3 column layout:
image

and added content to secondary sidebar:
image

I've tested on the temporary site that is hosted at godaddy with the same results.

image

### PR DESCRIPTION
**Pull request by EvanHerman**
Resolves #197

When a user selected any of the page templates with a secondary sidebar these weren't visible. (See #197 for screenshots).

The main issue was that we were checking `strpos` of 'three-columns' in the return of `primer_get_layout()`. Well when a three-column layout was selected, the position of the string was always 0, so the sidebar was never visible.

##### Example (Template: three-column-center)

```php
0 === strpos( primer_get_layout(), 'three-column-' )
```

☝️ Always returned 0 when the string was found. If the string was not found then a value of `FALSE` was returned.

##### Solution
The solution was to check if the returned value was a boolean or not.

```php
is_bool( strpos( primer_get_layout(), 'three-column' ) )
```

Inside of [sidebar-tertiary.php](https://github.com/godaddy/wp-primer-theme/blob/5d4070b8087469dc19057731b463b29f37763379/sidebar-tertiary.php#L11)

```php
if ( ! primer_layout_has_sidebar() || ! is_active_sidebar( 'sidebar-2' ) || is_bool( strpos( primer_get_layout(), 'three-column' ) ) ) {

	return;

}
```

### CODE REVIEW

File: sidebar-tertiary.php [hunk 1]
```diff
@@ -8,7 +8,7 @@
  * @since   1.0.0
  */
 
-if ( ! primer_layout_has_sidebar() || ! is_active_sidebar( 'sidebar-2' ) || 0 === strpos( primer_get_layout(), 'three-column-' ) ) {
+if ( ! primer_layout_has_sidebar() || ! is_active_sidebar( 'sidebar-2' ) || is_bool( strpos( primer_get_layout(), 'three-column' ) ) ) {
```
Comment (frankiejarrett) [inline sidebar-tertiary.php]: I think the fix is to actually just swap `===` with `!==` - we want to bail if the layout does not start with `three-column-`

**Review by frankiejarrett — CHANGES_REQUESTED** [review]

**Review by frankiejarrett — APPROVED** [review]
