### PR TITLE
Fix WooCommerce shop page titles, and remove duplicate shop title

### LINKED ISSUE #88: Fix the page title on WooCommerce 'Shop' pages
The title on the 'Shop' page defaults to 'Archives: Products'. We should introduce a filter into the woocommerce.php file that will filter the page title to inherit the title from the current 'Shop' page set in the WooCommerce settings. (`wc_get_page_id( 'shop' )`)

We can also use the WooCommerce filter `woocommerce_page_title` to remove the default 'Shop' title inside of the shop loop. This would allow WooCommerce to fit better into primer, and it's child themes.

WooCommerce shop page title

Could be:
WooCommerce shop page title updated

### PR DESCRIPTION
**Pull request by EvanHerman**
Fixes #88

### CODE REVIEW

File: inc/woocommerce.php [hunk 1]
```diff
@@ -73,3 +73,39 @@ function primer_woo_shop_layout( $layout ) {
...
+ * @return string
+ */
+function primer_woo_shop_title( $title ) {
+
+	if ( function_exists( 'wc_get_page_id' ) && function_exists( 'is_shop' ) && is_shop() ) {
+
+		$title = get_the_title( wc_get_page_id( 'shop' ) );
+
+		// Remove the WooCommerce shop loop title
+		add_filter( 'woocommerce_page_title', 'primer_woo_shop_loop_title' );
```
Comment (frankiejarrett) [inline inc/woocommerce.php]: @EvanHerman we can just use `__return_null` as the callback here.

File: inc/woocommerce.php [hunk 2]
```diff
@@ -73,3 +73,39 @@ function primer_woo_shop_layout( $layout ) {
...
+add_filter( 'primer_the_page_title', 'primer_woo_shop_title' );
+
+/**
+ * Filter the page title for the WooCommerce page.
+ *
+ * @param  string $title
+ *
+ * @return null
+ */
+function primer_woo_shop_loop_title( $title ) {
```
Comment (frankiejarrett) [inline inc/woocommerce.php]: @EvanHerman then this function isn't needed

File: inc/woocommerce.php [hunk 3]
```diff
@@ -73,3 +73,39 @@ function primer_woo_shop_layout( $layout ) {
 
 }
 add_filter( 'theme_mod_layout', 'primer_woo_shop_layout' );
+
+/**
+ * Filter the page title for the WooCommerce shop page.
+ *
```
Comment (frankiejarrett) [inline inc/woocommerce.php:98]: @EvanHerman add these lines:

```
* @filter primer_the_page_title
* @since  1.0.0
```

File: inc/woocommerce.php [hunk 4]
```diff
@@ -73,3 +73,39 @@ function primer_woo_shop_layout( $layout ) {
...
+ * @return string
+ */
+function primer_woo_shop_title( $title ) {
+
+	if ( function_exists( 'wc_get_page_id' ) && function_exists( 'is_shop' ) && is_shop() ) {
+
+		$title = get_the_title( wc_get_page_id( 'shop' ) );
+
+		// Remove the WooCommerce shop loop title
```
Comment (frankiejarrett) [inline inc/woocommerce.php:113]: @EvanHerman once we are using the `__return_null` callback, this comment won't be necessary.

**Comment by frankiejarrett** [comment]
@EvanHerman it looks like I forgot to add `@filter`, `@action` and `@since` docblocks to a lot of functions in the `inc/woocommerce.php` file. This would be a good time to add them.

**Comment by frankiejarrett** [comment]
@EvanHerman resolve conflicts and I'll merge
