### PR TITLE
Fix backward compatibility when using Beaver Builder on PHP 5.3 or lower

### LINKED ISSUE #196: Primer Child Theme Uptown Styles Throws Errors
Fatal error: Cannot access protected property Primer_Customizer_Layouts::$layouts in /home/content/80/8803880/html/L4p/wp-content/themes/primer/inc/compat/beaver-builder.php on line 34

Is an error i am getting running Primer 1.7.0 (Runs fine on my other site running beaver builder) but the UpTown Style child theme verion 1.1.0 causes the above error

### PR DESCRIPTION
**Pull request by EvanHerman**
Resolves #196 

Enables backwards compatibility for Beaver Builder. 

Tested and working back to **PHP v5.2.4** ([Beaver Builder minimum requirement](http://kb.wpbeaverbuilder.com/article/253-system-requirements-for-beaver-builder))

### CODE REVIEW

File: inc/customizer/layouts.php [hunk 1]
```diff
@@ -564,6 +566,27 @@ public function get_current_layout( $post = null ) {
 
 	}
 
+	/**
+	 * Magic getter for `$colors` and `$color_schemes` properties.
+	 *
+	 * @since  1.0.0
```
Comment (frankiejarrett) [inline inc/customizer/layouts.php]: Should be `@since NEXT`

File: inc/helpers.php [hunk 2]
```diff
@@ -576,7 +576,9 @@ function primer_array_replace_recursive( array $array1, array $array2 ) {
 
 	if ( function_exists( 'array_replace_recursive' ) ) {
 
-		return call_user_func_array( 'array_replace_recursive', func_get_args() );
+		$args = func_get_args();
+
+		return call_user_func_array( 'array_replace_recursive', $args );
```
Comment (frankiejarrett) [inline inc/helpers.php:581]: Nice catch!

File: inc/customizer/layouts.php [hunk 3]
```diff
@@ -564,6 +566,27 @@ public function get_current_layout( $post = null ) {
...
+	 */
+	public function __get( $name ) {
+
+		if ( ! in_array( $name, array( 'layouts', 'default', 'meta_box', 'page_widths' ), true ) ) {
+
+			return false;
+
+		}
+
+		return $this->$name;
```
Comment (frankiejarrett) [inline inc/customizer/layouts.php]: This can be a two-liner:

```php
$properties = array( 'layouts', 'default', 'meta_box', 'page_widths' );

return in_array( $name, $properties, true ) ? $this->$name : false;
```

**Review by frankiejarrett — CHANGES_REQUESTED** [review]

File: inc/customizer/layouts.php [hunk 4]
```diff
@@ -172,7 +172,9 @@ public function post_type_support() {
 		 *
 		 * @var array
 		 */
-		$post_types = (array) apply_filters( 'primer_layouts_post_types', get_post_types( array( 'public' => true ) ) );
+		$post_types = (array) apply_filters( 'primer_layouts_post_types', get_post_types( array(
+			'public' => true,
+		) ) );
```
Comment (frankiejarrett) [inline inc/customizer/layouts.php]: @EvanHerman I think it would be good to get into the habit of staying within the scope of the PR. When you least expect it a trivial fix will accidentally break something (I should know!) - then the change is harder to roll back because it was really just a hitchhiker on a commit in a branch that had a different purpose.

A suggestion would be to keep a branch hanging around locally, like `evans-tweaks`, where you can stash these type of trivial changes and to do each change in its own commit so it's really easy to revert if you ever need to. Then just merge it to `develop` periodically, perhaps after a series of other PRs.

Just my 2¢.
