### PR TITLE
Only load video header functionality when using WordPress 4.7 or higher

### LINKED ISSUE #195: Error on Theme update
WordPress site auto updated to 1.7.0 and threw the following error: Fatal error: Call to undefined function has_header_video() in /home/username/public_html/wp-content/themes/primer/functions.php on line 484
Rolled primer theme  back to 1.6.0 and the site came back up.

### PR DESCRIPTION
**Pull request by EvanHerman**
Resolves #195 

In the 1.7.0 release checking that the function `has_header_video` is available before using it was overlooked. This PR adds `function_exists()` checks for `has_header_video` where necessary.

Additionally a minor PHPCS error was resolved (associative arrays on individual lines), which was introduced with the latest release of PHPCS.

### CODE REVIEW

File: functions.php [hunk 1]
```diff
@@ -481,7 +488,7 @@ function primer_scripts() {
 
 	wp_style_add_data( $stylesheet, 'rtl', 'replace' );
 
-	$nav_dependencies = ( is_front_page() && has_header_video() ) ? array( 'jquery', 'wp-custom-header' ) : array( 'jquery' );
+	$nav_dependencies = ( is_front_page() && ( function_exists( 'has_header_video' ) && has_header_video() ) ) ? array( 'jquery', 'wp-custom-header' ) : array( 'jquery' );
```
Comment (frankiejarrett) [inline functions.php]: The last two conditions don't have to be grouped, when the second one fails the third won't be attempted.

```php
is_front_page() && function_exists( 'has_header_video' ) && has_header_video()
```

**Review by frankiejarrett — CHANGES_REQUESTED** [review]

File: functions.php [hunk 2]
```diff
@@ -443,7 +443,14 @@ function primer_register_sidebars() {
...
 
-		register_sidebar( array_merge( array( 'id' => $id ), $args ) );
+		register_sidebar(
+			array_merge(
+				array(
+					'id' => $id,
+				),
+				$args
+			)
+		);
```
Comment (frankiejarrett) [inline functions.php]: @EvanHerman I find this expanded view less readable, just me?

Comment (frankiejarrett) [reply functions.php]: Is this change within the scope of the PR?

Comment (EvanHerman) [reply functions.php]: @fjarrett No, you are correct. This is more difficult to read. During the changes in this PR the new version of the WordPress coding standards was released, and I cam across this change. As per your other comment (on the PR for [Issue #200](https://github.com/godaddy/wp-primer-theme/pull/200)) you are correct. I've gone ahead and reverted this change to remain in scope of the PR.
